# Generated by Django 5.1.1 on 2025-09-06 20:41

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/', validators=[utils.validators.validate_image]),
        ),
    ]
