# Generated by Django 5.1.1 on 2025-03-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
